export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_EXPENSES = "SET_EXPENSES";
export const SET_INCOMES = "SET_INCOMES";
export const REMOVE_TRANSACTION = "REMOVE_TRANSACTION";
export const ADD_EXPENSE = "ADD_EXPENSE";
export const ADD_INCOME = "ADD_INCOME";
